version: "3.2"
services:
  mongo:
    image: mongo:latest
    ports:
      - "2017:27017"

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=tedemo

